source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'JBFancy_Example' do
  pod 'JBFancy', :git => 'https://github.com/saintjab/JBFancy'

  target 'JBFancy_Tests' do
    inherit! :search_paths

    
  end
end
